name: end to end test cases
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      CYPRESS_RUN:
        required: true
      PORT:
        required: false
jobs:
  e2e:
    name: run end to end test cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ github.event.repository.name }}-packages-v1
      - name: Install Dependencies
        run: |
          set -euxo pipefail
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          yarn config set cache-folder ~/.cache/yarn
          yarn install --pure-lockfile --ignore-engines
          rm ~/.npmrc
      - name: build the application
        run: NODE_CONFIG_ENV=test yarn run build
      - name: start mock server
        run: yarn run start:mock &
      - name: start web server
        run: SERVER_SSL=true PORT=${{secrets.PORT}} CONFIG_SERVICE_MOCK_FILE=__mocks__/mockConfig.json CONFIG_SERVICE_MOCK=true NODE_ENV=production NODE_CONFIG_ENV=test node server.js &
      - name: end to end tests
        run: ${{secrets.CYPRESS_RUN}}
