name: end to end test cases
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      CYPRESS_RUN:
        required: true
      PORT:
        required: false
jobs:
  e2e:
    name: run end to end test cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: node -v
      - name: Install Dependencies
        run: yarn install --pure-lockfile --ignore-engines
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: build the application
        run: NODE_CONFIG_ENV=test yarn run build
      - name: start mock server
        run: yarn run start:mock &
      - name: start web server
        run: SERVER_SSL=true CONFIG_SERVICE_MOCK_FILE=__mocks__/mockConfig.json CONFIG_SERVICE_MOCK=true NODE_ENV=production NODE_CONFIG_ENV=test node server.js &
        env:
          PORT: ${{ secrets.PORT }}
      - name: end to end tests
        run: ${{secrets.CYPRESS_RUN}}
