name: node
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: false
jobs:
  set-node-version:
    name: set node version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: node -v
