name: unit testing
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
jobs:
  unit_test:
    name: run unit test cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
        env:
          FORCE_COLOR: 0
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key:  ${{ github.event.repository.name }}-packages-v1
      - name: Install Dependencies
        run: yarn install --pure-lockfile --ignore-engines
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: NPM Audit Test
        run: /bin/sh -c 'yarn audit --level high; [[ $? -ge 8 ]] && exit 1 || exit 0'
      - name: Unit tests
        run: yarn  run test --runInBand --coverage --detectOpenHandles
